use msys2/setup-msys2@v2 (#50)
* use msys2/setup-msys2@v2

* use LTLIBICONV instead of LIBICONV

* fix: undefined reference to `wWinMain'

* fix WPATH

* fix CreateFile redefined

* use file command

* revert changes of Makefile

* fix

* Revert "fix"

This reverts commit 33d889a09b8f18efca70af95373225dbd9656c28.

* Revert "revert changes of Makefile"

This reverts commit 55e891ffd4f5f0dfc229a1e212f7fc74eeffc2d7.